FOREX_PAIRS = [
    # ── Metals (XM Real) ──────────────────────────────────────
    "XAU/USD",   # Gold
    "XAG/USD",   # Silver
    "XPT/USD",   # Platinum
    "XPD/USD",   # Palladium
    # ── Major Pairs ───────────────────────────────────────────
    "EUR/USD",
    "GBP/USD",
    "USD/JPY",
    "USD/CHF",
    "USD/CAD",
    "AUD/USD",
    "NZD/USD",
    # ── EUR Crosses ───────────────────────────────────────────
    "EUR/GBP",
    "EUR/JPY",
    "EUR/AUD",
    "EUR/CAD",
    "EUR/CHF",
    "EUR/NZD",
    "EUR/SEK",
    "EUR/NOK",
    "EUR/TRY",
    "EUR/PLN",
    # ── GBP Crosses ───────────────────────────────────────────
    "GBP/JPY",
    "GBP/AUD",
    "GBP/CAD",
    "GBP/CHF",
    "GBP/NZD",
    # ── AUD Crosses ───────────────────────────────────────────
    "AUD/JPY",
    "AUD/CAD",
    "AUD/CHF",
    "AUD/NZD",
    # ── NZD Crosses ───────────────────────────────────────────
    "NZD/JPY",
    "NZD/CAD",
    "NZD/CHF",
    # ── CAD Crosses ───────────────────────────────────────────
    "CAD/JPY",
    "CAD/CHF",
    # ── CHF Crosses ───────────────────────────────────────────
    "CHF/JPY",
    # ── USD Exotic Pairs (XM Real) ────────────────────────────
    "USD/TRY",
    "USD/SGD",
    "USD/HKD",
    "USD/NOK",
    "USD/SEK",
    "USD/DKK",
    "USD/MXN",
    "USD/ZAR",
    "USD/PLN",
    "USD/HUF",
    "USD/CZK",
    "USD/INR",
    "USD/PKR",
    "USD/BRL",
    "USD/ARS",
    "USD/COP",
    "USD/EGP",
    "USD/NGN",
    "USD/BDT",
    "USD/DZD",
    "USD/IDR",
    "USD/PHP",
]

CRYPTO_PAIRS = [
    "Bitcoin Cash (OTC)",
    "Binance Coin (OTC)",
    "Bitcoin (OTC)",
    "Litecoin (OTC)",
    "Solana (OTC)",
    "Axie Infinity (OTC)",
    "Polkadot (OTC)",
    "Ripple (OTC)",
    "Ethereum Classic (OTC)",
    "Cosmos (OTC)",
    "Zcash (OTC)",
    "Chainlink (OTC)",
    "Avalanche (OTC)",
    "Trump (OTC)",
    "Ethereum (OTC)",
    "Toncoin (OTC)",
    "Dash (OTC)",
]

BINANCE_SPOT_PAIRS = [
    "BTC/USDT",
    "ETH/USDT",
    "BNB/USDT",
    "SOL/USDT",
    "XRP/USDT",
    "BCH/USDT",
    "LTC/USDT",
    "AVAX/USDT",
    "DOT/USDT",
    "LINK/USDT",
    "ETC/USDT",
    "ATOM/USDT",
    "ZEC/USDT",
    "DASH/USDT",
    "TON/USDT",
    "AXS/USDT",
    "DOGE/USDT",
    "ADA/USDT",
    "TRX/USDT",
    "UNI/USDT",
]

QUOTEX_PAIRS = [
    # ── OTC Pairs (highest payout) ────────────────────────────
    "EUR/USD OTC",
    "GBP/USD OTC",
    "USD/JPY OTC",
    "AUD/USD OTC",
    "AUD/JPY OTC",
    "AUD/CAD OTC",
    "AUD/CHF OTC",
    "AUD/NZD OTC",
    "EUR/GBP OTC",
    "EUR/AUD OTC",
    "EUR/CAD OTC",
    "EUR/CHF OTC",
    "EUR/NZD OTC",
    "EUR/JPY OTC",
    "GBP/JPY OTC",
    "GBP/AUD OTC",
    "GBP/CAD OTC",
    "GBP/CHF OTC",
    "GBP/NZD OTC",
    "NZD/USD OTC",
    "NZD/CAD OTC",
    "NZD/CHF OTC",
    "NZD/JPY OTC",
    "CAD/CHF OTC",
    "CAD/JPY OTC",
    "CHF/JPY OTC",
    "USD/CAD OTC",
    "USD/CHF OTC",
    # ── Exotic OTC ────────────────────────────────────────────
    "USD/BRL OTC",
    "USD/TRY OTC",
    "USD/EGP OTC",
    "USD/IDR OTC",
    "USD/NGN OTC",
    "USD/ARS OTC",
    "USD/BDT OTC",
    "USD/INR OTC",
    "CAD/CHF OTC",
    "USD/COP OTC",
    "USD/PKR OTC",
    "USD/DZD OTC",
    "USD/MXN OTC",
    "USD/PHP OTC",
    "USD/ZAR OTC",
    # ── Non-OTC Live Pairs ────────────────────────────────────
    "EUR/USD",
    "GBP/USD",
    "USD/JPY",
    "AUD/USD",
    "AUD/JPY",
    "AUD/CAD",
    "AUD/CHF",
    "AUD/NZD",
    "EUR/GBP",
    "EUR/JPY",
    "EUR/AUD",
    "EUR/CAD",
    "EUR/CHF",
    "EUR/NZD",
    "GBP/JPY",
    "GBP/AUD",
    "GBP/CAD",
    "GBP/CHF",
    "GBP/NZD",
    "NZD/USD",
    "NZD/CAD",
    "NZD/CHF",
    "NZD/JPY",
    "CAD/JPY",
    "CAD/CHF",
    "CHF/JPY",
    "USD/CAD",
    "USD/CHF",
]

SUPPORTED_DURATIONS = [
    "5 Seconds",
    "10 Seconds",
    "15 Seconds",
    "30 Seconds",
    "1 Minute",
    "5 Minutes",
    "15 Minutes",
]
